### ISSUE TITLE
SSE IA32 question

### ISSUE THREAD

**Issue by Mike-Reddick** [roytam1/mozilla45esr#3]
First, thanks so much to this work in keep browsers for XP, I have a question, now have an new download option on blog, called IA32, on forks Firefox 45 and Serpent, both work without SSE and SSE2?

**Comment by roytam1** [comment]
Firefox 45 IA32 should work on any 32bit x86 processor.
Serpent IA32 requires CMOV instruction, there is a list of supported processor in https://rtfreesoft.blogspot.com/p/browser-help.html

**Comment by Mike-Reddick** [comment]
thanks so much!
